# Generated by Django 4.1.2 on 2022-11-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_user_domain_alter_user_emp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_code',
            field=models.IntegerField(default=False, null=True, unique=True),
        ),
    ]
