# Generated by Django 4.1.2 on 2022-11-01 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_user_emp_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emp_code',
        ),
    ]
