# Generated by Django 4.1.2 on 2022-11-02 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_remove_user_emp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
