# Generated by Django 4.1.2 on 2022-11-02 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_user_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cv',
        ),
    ]
