# Generated by Django 4.1.2 on 2022-11-03 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0006_remove_interview_position'),
        ('adminpanel', '0006_remove_user_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('MD', 'MD'), ('TLeader', 'TLeader'), ('Employee', 'Employee'), ('Intern', 'Intern')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Seniour', 'Seniour'), ('Junior', 'Junior'), ('Intern', 'Intern')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
