# Generated by Django 4.1.2 on 2022-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0007_alter_interview_domain'),
        ('adminpanel', '0007_user_role_alter_user_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domain',
            field=models.CharField(choices=[('Python Develper', 'Python Developer'), ('Php Developer', 'Php Developer')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
