# Generated by Django 4.1.2 on 2022-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0002_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
