# Generated by Django 4.1.2 on 2022-11-02 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0003_interview_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cv',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
