# Generated by Django 4.1.2 on 2022-11-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0004_interview_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='cv',
        ),
    ]
