# Generated by Django 4.1.2 on 2022-11-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0005_remove_interview_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='position',
        ),
    ]
