# Generated by Django 4.1.2 on 2022-11-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0006_remove_interview_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='domain',
            field=models.CharField(choices=[('Python Develper', 'Python Developer'), ('Php Developer', 'Php Developer')], max_length=200, null=True),
        ),
    ]
