# Generated by Django 4.1.2 on 2022-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0008_remove_interview_interviewers_interview_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=200, null=True),
        ),
    ]
