# Generated by Django 4.1.2 on 2022-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0009_interview_interview_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='attempt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
