# Generated by Django 4.1.2 on 2022-11-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrpanel', '0010_alter_interview_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='model',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
